import { Student, AttendanceRecord, IncomeRecord, ExpenseRecord, UserSession, UserAccount, BimbelSettings } from '../types';
import { DEFAULT_WA_TEMPLATES } from './whatsapp';
import { PDF_ATTENDANCE_RECORDS } from './pdfAttendanceData';

export const DEFAULT_ACCOUNTS: UserAccount[] = [
  {
    role: 'owner',
    id: 'usr-owner-1',
    name: 'Budi Santoso, S.Pd. (Owner)',
    username: 'owner',
    password: 'sigma123',
    email: 'owner@bimbelsigma.id',
    phone: '081234567890',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    specialty: 'Kepala Bimbel & Manajemen Operasional',
    isActive: true,
    createdAt: '2026-01-01',
  },
  {
    role: 'tutor',
    id: 'usr-tutor-1',
    name: 'Kak Sarah Amalia, S.Si.',
    username: 'tutor',
    password: 'sigma123',
    email: 'sarah.tutor@bimbelsigma.id',
    phone: '085712349988',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    specialty: 'Tutor Matematika & Fisika (SMP/SMA)',
    isActive: true,
    createdAt: '2026-01-05',
  },
  {
    role: 'tutor',
    id: 'usr-tutor-2',
    name: 'Kak Dimas Pratama, M.Pd.',
    username: 'dimas',
    password: 'sigma123',
    email: 'dimas.tutor@bimbelsigma.id',
    phone: '081398765432',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    specialty: 'Tutor Calistung & Tematik SD',
    isActive: true,
    createdAt: '2026-01-05',
  },
  {
    role: 'siswa',
    id: 'usr-std-1',
    name: 'Naureen Zevania Putri Riansyah',
    username: 'siswa',
    password: 'sigma123',
    code: 'NAUREEN',
    linkedStudentId: 'std-1',
    phone: '081234567801',
    avatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=150&auto=format&fit=crop&q=80',
    specialty: 'PAUD - Bimbel Calistung',
    isActive: true,
    createdAt: '2026-01-10',
  },
  {
    role: 'siswa',
    id: 'usr-std-2',
    name: 'Zidane',
    username: 'zidane',
    password: 'sigma123',
    code: 'ZIDANE',
    linkedStudentId: 'std-23',
    phone: '081234567823',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    specialty: 'Kelas 8 SMP - Matematika & IPA',
    isActive: true,
    createdAt: '2026-01-10',
  },
];

export const DEFAULT_USERS: UserSession[] = DEFAULT_ACCOUNTS;

export const DEFAULT_SETTINGS: BimbelSettings = {
  bimbelName: 'BIMBEL SIGMA',
  tagline: 'Belajar Sampai Paham, Bukan Sekadar Hafal',
  ownerName: 'Budi Santoso, S.Pd.',
  ownerTitle: 'Pemilik & Direktur Lembaga',
  directorTitle: 'Direktur Operasional',
  financeOfficerName: 'Sarah Amalia, S.Si.',
  financeOfficerTitle: 'Bendahara / Finance & Admin',
  operationalManagerName: 'Dimas Pratama, M.Pd.',
  operationalManagerTitle: 'Manajer Akademik & Operasional',
  phone: '0812-3456-7890',
  email: 'admin@bimbelsigma.id',
  address: 'Karang Muso 06/02 Bicak, Todanan, Blora, Jawa Tengah',
  city: 'Blora',
  bankInfo: 'BCA: 8830-1234-56 a.n Bimbel Sigma Mandiri',
  systemSalaryCategory: 'Gaji / Honor Tutor',
  systemSppCategory: 'Pembayaran SPP Siswa',
  expenseCategories: [
    'Gaji / Honor Tutor',
    'Sewa Tempat / Gedung',
    'Listrik, Internet & Air',
    'Modul, ATK & Cetak',
    'Marketing / Iklan',
    'Snack & Konsumsi Siswa',
    'Kebersihan & Operasional',
    'Lain-lain',
  ],
  incomeCategories: [
    'Pembayaran SPP Siswa',
    'Biaya Pendaftaran / Registrasi',
    'Modul & Buku Paket',
    'Try Out & Ujian Simulasi',
    'Event / Workshop Bimbel',
    'Lainnya',
  ],
  paymentMethods: [
    'Tunai',
    'Transfer BCA',
    'Transfer Mandiri',
    'Transfer BRI',
    'Transfer BNI',
    'QRIS',
    'GoPay / OVO / Dana',
    'Lainnya',
  ],
  logoSymbol: 'Σ',
  appVersionBadge: 'v2.6 PRO',
  sidebarFooterTitle: 'BIMBEL SIGMA',
  sidebarFooterTagline: '“Belajar Sampai Paham”',
  sidebarFooterNote: 'Data tersimpan aman di LocalStorage browser',
  accentColor: 'indigo',
  ownerDashboardBadge: 'Executive Dashboard (Owner Access)',
  ownerDashboardTitle: '',
  ownerDashboardMessage: 'Pantau metrik finansial, absensi digital real-time, dan pembukuan tahunan dalam satu pintu.',
  tutorDashboardBadge: 'Ruang Kerja Pengajar (Tutor Access)',
  tutorDashboardTitle: '',
  tutorDashboardMessage: 'Fokus pada kualitas pembelajaran: catat absensi harian siswa, topik materi, serta evaluasi pemahaman belajar.',
  studentDashboardBadge: 'Portal Belajar Siswa',
  studentDashboardTitle: '',
  studentDashboardMessage: 'Selamat belajar! Pantau riwayat pertemuan, materi pelajaran, dan absensi belajarmu di sini.',
  loginWelcomeMessage: 'Sistem Manajemen & Presensi Digital Bimbel Terintegrasi',

  // Default Konfigurasi Gaji Tutor
  salaryCalculationMode: 'percentage',
  privatSalaryPercentage: 60, // 60% bagi hasil kelas privat
  groupSalaryPercentage: 40, // 40% bagi hasil kelas grup
  semiPrivatSalaryPercentage: 50, // 50% bagi hasil kelas semi-privat
  minPrivatSessionRate: 50000,
  minGroupSessionRate: 60000,
  flatPrivatSessionRate: 65000,
  flatGroupSessionRate: 80000,
  transportAllowancePerDay: 15000,
  evaluationBonusPerSession: 0,

  // Default Template Pesan WhatsApp
  whatsappTemplates: DEFAULT_WA_TEMPLATES,
};

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-1',
    code: 'NAUREEN',
    name: 'Naureen Zevania Putri Riansyah',
    level: 'PAUD',
    gradeDetail: 'PAUD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Naureen',
    parentPhone: '081234567801',
    address: 'Komplek Permata Blok A1',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Program PAUD / Calistung Dasar',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
  },
  {
    id: 'std-2',
    code: 'KIA',
    name: 'Kia',
    level: 'SD',
    gradeDetail: 'Kelas 2 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Kia',
    parentPhone: '081234567802',
    address: 'Jl. Melati No. 2',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Tematik & Matematika Dasar',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
  },
  {
    id: 'std-3',
    code: 'BRIAN',
    name: 'Brian',
    level: 'SD',
    gradeDetail: 'Kelas 2 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Brian',
    parentPhone: '081234567803',
    address: 'Jl. Melati No. 3',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Tematik Kelas 2',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
  },
  {
    id: 'std-4',
    code: 'GYO',
    name: 'Gyo',
    level: 'SD',
    gradeDetail: 'Kelas 2 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Gyo',
    parentPhone: '081234567804',
    address: 'Jl. Cempaka No. 4',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Tematik Kelas 2',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
  },
  {
    id: 'std-5',
    code: 'ABI',
    name: 'Abi',
    level: 'SD',
    gradeDetail: 'Kelas 3 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Abi',
    parentPhone: '081234567805',
    address: 'Jl. Kenanga No. 5',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Matematika & Tematik Kelas 3',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
  },
  {
    id: 'std-6',
    code: 'SILVIA',
    name: 'Silvia',
    level: 'SD',
    gradeDetail: 'Kelas 3 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Silvia',
    parentPhone: '081234567806',
    address: 'Jl. Anggrek No. 6',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 3 SD',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
  },
  {
    id: 'std-7',
    code: 'GEO',
    name: 'Geo',
    level: 'SD',
    gradeDetail: 'Kelas 3 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Geo',
    parentPhone: '081234567807',
    address: 'Jl. Flamboyan No. 7',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 3 SD',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
  },
  {
    id: 'std-8',
    code: 'ELVANO',
    name: 'Elvano',
    level: 'SD',
    gradeDetail: 'Kelas 3 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Elvano',
    parentPhone: '081234567808',
    address: 'Jl. Dahlia No. 8',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 3 SD',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
  },
  {
    id: 'std-9',
    code: 'KAYSA',
    name: 'Kaysa',
    level: 'SD',
    gradeDetail: 'Kelas 4 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Kaysa',
    parentPhone: '081234567809',
    address: 'Jl. Mawar No. 9',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 4 SD',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
  },
  {
    id: 'std-10',
    code: 'AGAN',
    name: 'Agan',
    level: 'SD',
    gradeDetail: 'Kelas 4 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Agan',
    parentPhone: '081234567810',
    address: 'Jl. Teratai No. 10',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 4 SD',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
  },
  {
    id: 'std-11',
    code: 'DOLKEN',
    name: 'Dolken',
    level: 'SD',
    gradeDetail: 'Kelas 4 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Dolken',
    parentPhone: '081234567811',
    address: 'Jl. Kamboja No. 11',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 4 SD',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
  },
  {
    id: 'std-12',
    code: 'RARA',
    name: 'Rara',
    level: 'SD',
    gradeDetail: 'Kelas 4 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Rara',
    parentPhone: '081234567812',
    address: 'Jl. Sakura No. 12',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 4 SD',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
  },
  {
    id: 'std-13',
    code: 'KAILA',
    name: 'Kaila',
    level: 'SD',
    gradeDetail: 'Kelas 4 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Kaila',
    parentPhone: '081234567813',
    address: 'Jl. Tulip No. 13',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 4 SD',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
  },
  {
    id: 'std-14',
    code: 'DEBI',
    name: 'Debi',
    level: 'SD',
    gradeDetail: 'Kelas 4 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Debi',
    parentPhone: '081234567814',
    address: 'Jl. Lily No. 14',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 4 SD',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
  },
  {
    id: 'std-15',
    code: 'TASYA',
    name: 'Tasya',
    level: 'SD',
    gradeDetail: 'Kelas 5 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Tasya',
    parentPhone: '081234567815',
    address: 'Jl. Wijaya No. 15',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 5 SD',
    tutorName: 'Kak Sarah Amalia, S.Si.',
  },
  {
    id: 'std-16',
    code: 'BELLA',
    name: 'Bella',
    level: 'SD',
    gradeDetail: 'Kelas 5 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Bella',
    parentPhone: '081234567816',
    address: 'Jl. Hasanudin No. 16',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 5 SD',
    tutorName: 'Kak Sarah Amalia, S.Si.',
  },
  {
    id: 'std-17',
    code: 'RAJA',
    name: 'Raja',
    level: 'SD',
    gradeDetail: 'Kelas 6 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Raja',
    parentPhone: '081234567817',
    address: 'Jl. Sudirman No. 17',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 6 SD / Persiapan Ujian',
    tutorName: 'Kak Sarah Amalia, S.Si.',
  },
  {
    id: 'std-18',
    code: 'AURA',
    name: 'Aura',
    level: 'SD',
    gradeDetail: 'Kelas 6 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Aura',
    parentPhone: '081234567818',
    address: 'Jl. Gatot Subroto No. 18',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 6 SD',
    tutorName: 'Kak Sarah Amalia, S.Si.',
  },
  {
    id: 'std-19',
    code: 'NAILA',
    name: 'Naila',
    level: 'SD',
    gradeDetail: 'Kelas 6 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Naila',
    parentPhone: '081234567819',
    address: 'Jl. Diponegoro No. 19',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 6 SD',
    tutorName: 'Kak Sarah Amalia, S.Si.',
  },
  {
    id: 'std-20',
    code: 'RANGGA',
    name: 'Rangga',
    level: 'SD',
    gradeDetail: 'Kelas 6 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Rangga',
    parentPhone: '081234567820',
    address: 'Jl. Pahlawan No. 20',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 6 SD',
    tutorName: 'Kak Sarah Amalia, S.Si.',
  },
  {
    id: 'std-21',
    code: 'JUNA',
    name: 'Juna',
    level: 'SD',
    gradeDetail: 'Kelas 6 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Juna',
    parentPhone: '081234567821',
    address: 'Jl. Ahmad Yani No. 21',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 6 SD',
    tutorName: 'Kak Sarah Amalia, S.Si.',
  },
  {
    id: 'std-22',
    code: 'AGHA',
    name: 'Agha',
    level: 'SD',
    gradeDetail: 'Kelas 6 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Agha',
    parentPhone: '081234567822',
    address: 'Jl. Kartini No. 22',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Kelas 6 SD',
    tutorName: 'Kak Sarah Amalia, S.Si.',
  },
  {
    id: 'std-23',
    code: 'ZIDANE',
    name: 'Zidane',
    level: 'SMP',
    gradeDetail: 'Kelas 8 SMP',
    classType: 'Privat',
    pricePerSession: 10000,
    monthlyFee: 80000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Zidane',
    parentPhone: '081234567823',
    address: 'Jl. Imam Bonjol No. 23',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel SMP Matematika & IPA',
    tutorName: 'Kak Sarah Amalia, S.Si.',
  },
  {
    id: 'std-24',
    code: 'VALEN',
    name: 'Valen',
    level: 'SMP',
    gradeDetail: 'Kelas 9 SMP',
    classType: 'Privat',
    pricePerSession: 8000,
    monthlyFee: 64000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Valen',
    parentPhone: '081234567824',
    address: 'Jl. Teuku Umar No. 24',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel SMP Persiapan Ujian Kelulusan',
    tutorName: 'Kak Sarah Amalia, S.Si.',
  },
  {
    id: 'std-25',
    code: 'ATHAR',
    name: 'Athar',
    level: 'SD',
    gradeDetail: 'Kelas 3 SD',
    classType: 'Grup',
    pricePerSession: 5000,
    monthlyFee: 40000,
    packageType: 'monthly',
    sessionQuota: 8,
    remainingSessions: 8,
    parentName: 'Orang Tua Athar',
    parentPhone: '081234567825',
    address: 'Jl. Hayam Wuruk No. 25',
    status: 'Aktif',
    joinDate: '2026-01-10',
    notes: 'Bimbel Tematik Kelas 3 SD',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [];

export const INITIAL_INCOMES: IncomeRecord[] = [];

export const INITIAL_EXPENSES: ExpenseRecord[] = [];

