import { AttendanceRecord } from '../types';

export const PDF_ATTENDANCE_RECORDS: AttendanceRecord[] = [
  // --- Page 1: Records 1 to 53 ---
  {
    id: 'att-pdf-001',
    date: '2026-07-07',
    time: '14:00',
    studentId: 'std-1',
    studentCode: 'NAUREEN',
    studentName: 'Naureen Zevania Putri Riansyah',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Calistung Dasar & Pengenalan Huruf',
    tutorNotes: 'Aktif dan ceria, mengenal huruf vokal A-I-U-E-O.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-07-07T14:00:00Z',
  },
  {
    id: 'att-pdf-002',
    date: '2026-07-18',
    time: '15:00',
    studentId: 'std-23',
    studentCode: 'ZIDANE',
    studentName: 'Zidane',
    classType: 'Privat',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Perkalian dan mengenal bentuk akar',
    tutorNotes: 'Memahami konsep dasar perkalian akar kuadrat.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-07-18T15:00:00Z',
  },
  {
    id: 'att-pdf-003',
    date: '2026-07-25',
    time: '15:00',
    studentId: 'std-23',
    studentCode: 'ZIDANE',
    studentName: 'Zidane',
    classType: 'Privat',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Perkalian dan mengenal bentuk akar',
    tutorNotes: 'Latihan soal penyederhanaan bentuk akar.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-07-25T15:00:00Z',
  },
  {
    id: 'att-pdf-004',
    date: '2026-07-26',
    time: '16:00',
    studentId: 'std-24',
    studentCode: 'VALEN',
    studentName: 'Valen',
    classType: 'Privat',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Persamaan linear 2 variabel',
    tutorNotes: 'Metode eliminasi dan substitusi SPLDV.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-07-26T16:00:00Z',
  },
  {
    id: 'att-pdf-005',
    date: '2026-08-02',
    time: '16:00',
    studentId: 'std-24',
    studentCode: 'VALEN',
    studentName: 'Valen',
    classType: 'Privat',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Bilangan berpangkat',
    tutorNotes: 'Sifat-sifat eksponen bilangan bulat positif & negatif.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-02T16:00:00Z',
  },
  {
    id: 'att-pdf-006',
    date: '2026-08-03',
    time: '14:30',
    studentId: 'std-17',
    studentCode: 'RAJA',
    studentName: 'Raja',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Perkalian pecahan biasa',
    tutorNotes: 'Mampu menyederhanakan pembilang dan penyebut.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-03T14:30:00Z',
  },
  {
    id: 'att-pdf-007',
    date: '2026-08-03',
    time: '14:30',
    studentId: 'std-2',
    studentCode: 'KIA',
    studentName: 'Kia',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Perkalian',
    tutorNotes: 'Menghafal dan memahami konsep perkalian dasar.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-03T14:30:00Z',
  },
  {
    id: 'att-pdf-008',
    date: '2026-08-03',
    time: '14:30',
    studentId: 'std-18',
    studentCode: 'AURA',
    studentName: 'Aura',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Mengubah bentuk pecahan campuran',
    tutorNotes: 'Konversi pecahan campuran ke pecahan biasa.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-03T14:30:00Z',
  },
  {
    id: 'att-pdf-009',
    date: '2026-08-03',
    time: '14:30',
    studentId: 'std-3',
    studentCode: 'BRIAN',
    studentName: 'Brian',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Perkalian',
    tutorNotes: 'Latihan perkalian angka 1-5 dengan lancar.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-03T14:30:00Z',
  },
  {
    id: 'att-pdf-010',
    date: '2026-08-03',
    time: '14:30',
    studentId: 'std-15',
    studentCode: 'TASYA',
    studentName: 'Tasya',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Pembagian level 2',
    tutorNotes: 'Operasi pembagian bersusun porogapit level 2.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-03T14:30:00Z',
  },
  {
    id: 'att-pdf-011',
    date: '2026-08-03',
    time: '14:30',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Perkalian level 2',
    tutorNotes: 'Peningkatan kecepatan berhitung perkalian puluhan.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-03T14:30:00Z',
  },
  {
    id: 'att-pdf-012',
    date: '2026-08-03',
    time: '14:30',
    studentId: 'std-4',
    studentCode: 'GYO',
    studentName: 'Gyo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: "Bahasa inggris likes dan doesn't like",
    tutorNotes: 'Pemahaman kalimat simple present tense kesukaan.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-03T14:30:00Z',
  },
  {
    id: 'att-pdf-013',
    date: '2026-08-03',
    time: '14:30',
    studentId: 'std-20',
    studentCode: 'RANGGA',
    studentName: 'Rangga',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Perkalian pecahan',
    tutorNotes: 'Perkalian pecahan biasa dengan bilangan bulat.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-03T14:30:00Z',
  },
  {
    id: 'att-pdf-014',
    date: '2026-08-03',
    time: '14:30',
    studentId: 'std-8',
    studentCode: 'ELVANO',
    studentName: 'Elvano',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Pendalaman Tematik & Latihan Soal',
    tutorNotes: 'Mengerjakan modul tematik terpadu.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-03T14:30:00Z',
  },
  {
    id: 'att-pdf-015',
    date: '2026-08-04',
    time: '15:00',
    studentId: 'std-18',
    studentCode: 'AURA',
    studentName: 'Aura',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Perkalian pecahan',
    tutorNotes: 'Perkalian pecahan campuran dengan pecahan biasa.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-04T15:00:00Z',
  },
  {
    id: 'att-pdf-016',
    date: '2026-08-04',
    time: '15:00',
    studentId: 'std-10',
    studentCode: 'AGAN',
    studentName: 'Agan',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Operasi hitung campur',
    tutorNotes: 'Kaidah urutan operasi hitung penjumlahan dan perkalian.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-04T15:00:00Z',
  },
  {
    id: 'att-pdf-017',
    date: '2026-08-04',
    time: '15:00',
    studentId: 'std-3',
    studentCode: 'BRIAN',
    studentName: 'Brian',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Perkalian level 1',
    tutorNotes: 'Latihan soal berhitung cepat perkalian 1-5.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-04T15:00:00Z',
  },
  {
    id: 'att-pdf-018',
    date: '2026-08-04',
    time: '15:00',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Perkalian, membaca dan menulis',
    tutorNotes: 'Latihan literasi bahasa dan numerasi perkalian.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-04T15:00:00Z',
  },
  {
    id: 'att-pdf-019',
    date: '2026-08-04',
    time: '15:00',
    studentId: 'std-4',
    studentCode: 'GYO',
    studentName: 'Gyo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Perkalian, bahasa indonesia',
    tutorNotes: 'Latihan membaca pemahaman dan perkalian dasar.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-04T15:00:00Z',
  },
  {
    id: 'att-pdf-020',
    date: '2026-08-04',
    time: '15:00',
    studentId: 'std-9',
    studentCode: 'KAYSA',
    studentName: 'Kaysa',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Operasi hitung campur',
    tutorNotes: 'Mengerjakan 10 soal hitung campuran dengan benar.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-04T15:00:00Z',
  },
  {
    id: 'att-pdf-021',
    date: '2026-08-05',
    time: '15:00',
    studentId: 'std-8',
    studentCode: 'ELVANO',
    studentName: 'Elvano',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Pendalaman Tematik & Latihan Soal',
    tutorNotes: 'Mengerjakan modul tematik bab 1.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-05T15:00:00Z',
  },
  {
    id: 'att-pdf-022',
    date: '2026-08-05',
    time: '15:00',
    studentId: 'std-3',
    studentCode: 'BRIAN',
    studentName: 'Brian',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'Perkalian membaca dan menulis',
    tutorNotes: 'Latihan dikte kata dan perkalian bersusun.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-05T15:00:00Z',
  },
  {
    id: 'att-pdf-023',
    date: '2026-08-05',
    time: '15:00',
    studentId: 'std-10',
    studentCode: 'AGAN',
    studentName: 'Agan',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Operasi hitung campur',
    tutorNotes: 'Menyelesaikan soal cerita hitungan campuran.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-05T15:00:00Z',
  },
  {
    id: 'att-pdf-024',
    date: '2026-08-05',
    time: '15:00',
    studentId: 'std-7',
    studentCode: 'GEO',
    studentName: 'Geo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: "Bahasa inggris likes dan doesn't like",
    tutorNotes: 'Menyusun kalimat percakapan bahasa Inggris.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-05T15:00:00Z',
  },
  {
    id: 'att-pdf-025',
    date: '2026-08-05',
    time: '15:00',
    studentId: 'std-9',
    studentCode: 'KAYSA',
    studentName: 'Kaysa',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Operasi hitung campur',
    tutorNotes: 'Tingkat akurasi berhitung sangat baik.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-05T15:00:00Z',
  },
  {
    id: 'att-pdf-026',
    date: '2026-08-05',
    time: '15:00',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'Perkalian, membaca dan menulis',
    tutorNotes: 'Latihan menulis kalimat tegak bersambung dan perkalian.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-05T15:00:00Z',
  },
  {
    id: 'att-pdf-027',
    date: '2026-08-05',
    time: '15:00',
    studentId: 'std-4',
    studentCode: 'GYO',
    studentName: 'Gyo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'Perkalian dan membaca',
    tutorNotes: 'Membaca lancar paragraf pendek dan perkalian.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-05T15:00:00Z',
  },
  {
    id: 'att-pdf-028',
    date: '2026-08-05',
    time: '15:00',
    studentId: 'std-20',
    studentCode: 'RANGGA',
    studentName: 'Rangga',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Perkalian desimal',
    tutorNotes: 'Menempatkan tanda koma pada hasil kali bilangan desimal.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-05T15:00:00Z',
  },
  {
    id: 'att-pdf-029',
    date: '2026-08-06',
    time: '15:30',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Perkalian, membaca dan menulis',
    tutorNotes: 'Menyelesaikan modul perkalian level 2.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-06T15:30:00Z',
  },
  {
    id: 'att-pdf-030',
    date: '2026-08-06',
    time: '15:30',
    studentId: 'std-17',
    studentCode: 'RAJA',
    studentName: 'Raja',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Perkalian desimal',
    tutorNotes: 'Latihan perkalian angka desimal satu & dua angka.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-06T15:30:00Z',
  },
  {
    id: 'att-pdf-031',
    date: '2026-08-06',
    time: '15:30',
    studentId: 'std-2',
    studentCode: 'KIA',
    studentName: 'Kia',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Perkalian',
    tutorNotes: 'Perkalian 6 sampai 8 semakin meningkat.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-06T15:30:00Z',
  },
  {
    id: 'att-pdf-032',
    date: '2026-08-06',
    time: '15:30',
    studentId: 'std-3',
    studentCode: 'BRIAN',
    studentName: 'Brian',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Perkalian',
    tutorNotes: 'Latihan soal berhitung mandiri.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-06T15:30:00Z',
  },
  {
    id: 'att-pdf-033',
    date: '2026-08-06',
    time: '15:30',
    studentId: 'std-12',
    studentCode: 'RARA',
    studentName: 'Rara',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Bilangan cacah sampai 10.000',
    tutorNotes: 'Membaca dan menulis lambang bilangan ribuan.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-06T15:30:00Z',
  },
  {
    id: 'att-pdf-034',
    date: '2026-08-06',
    time: '15:30',
    studentId: 'std-11',
    studentCode: 'DOLKEN',
    studentName: 'Dolken',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Bilangan cacah sampai 10.000',
    tutorNotes: 'Membandingkan dan mengurutkan bilangan cacah.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-06T15:30:00Z',
  },
  {
    id: 'att-pdf-035',
    date: '2026-08-06',
    time: '15:30',
    studentId: 'std-4',
    studentCode: 'GYO',
    studentName: 'Gyo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Perkalian',
    tutorNotes: 'Perkalian 1-5 selesai dengan sangat baik.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-06T15:30:00Z',
  },
  {
    id: 'att-pdf-036',
    date: '2026-08-06',
    time: '15:30',
    studentId: 'std-14',
    studentCode: 'DEBI',
    studentName: 'Debi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Bilangan cacah sampai 10.000',
    tutorNotes: 'Nilai tempat ribuan, ratusan, puluhan, satuan.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-06T15:30:00Z',
  },
  {
    id: 'att-pdf-037',
    date: '2026-08-07',
    time: '15:30',
    studentId: 'std-8',
    studentCode: 'ELVANO',
    studentName: 'Elvano',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'Pendalaman Tematik & Latihan Soal',
    tutorNotes: 'Diskusi soal tema lingkungan hidup.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-07T15:30:00Z',
  },
  {
    id: 'att-pdf-038',
    date: '2026-08-07',
    time: '15:30',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 5,
    topic: 'Perkalian level 3, membaca dan menulis',
    tutorNotes: 'Naik ke perkalian level 3 dengan pendampingan.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-07T15:30:00Z',
  },
  {
    id: 'att-pdf-039',
    date: '2026-08-07',
    time: '15:30',
    studentId: 'std-17',
    studentCode: 'RAJA',
    studentName: 'Raja',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'Operasi pecahan dan desimal',
    tutorNotes: 'Operasi gabungan pecahan campuran dan desimal.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-07T15:30:00Z',
  },
  {
    id: 'att-pdf-040',
    date: '2026-08-07',
    time: '15:30',
    studentId: 'std-6',
    studentCode: 'SILVIA',
    studentName: 'Silvia',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Perkalian, mengenal nilai tempat dan angka',
    tutorNotes: 'Pengenalan konsep ratusan dan perkalian dasar.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-07T15:30:00Z',
  },
  {
    id: 'att-pdf-041',
    date: '2026-08-07',
    time: '15:30',
    studentId: 'std-7',
    studentCode: 'GEO',
    studentName: 'Geo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Perkalian level 2',
    tutorNotes: 'Latihan soal perkalian level 2.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-07T15:30:00Z',
  },
  {
    id: 'att-pdf-042',
    date: '2026-08-07',
    time: '15:30',
    studentId: 'std-11',
    studentCode: 'DOLKEN',
    studentName: 'Dolken',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Penjumlahan, pengurangan ratusan',
    tutorNotes: 'Operasi hitung penjumlahan teknik menyimpan.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-07T15:30:00Z',
  },
  {
    id: 'att-pdf-043',
    date: '2026-08-09',
    time: '16:00',
    studentId: 'std-24',
    studentCode: 'VALEN',
    studentName: 'Valen',
    classType: 'Privat',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'PR inggris, merasionalkan penyebut akar',
    tutorNotes: 'Bahas PR bahasa Inggris dan rasionalisasi akar pecahan.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-09T16:00:00Z',
  },
  {
    id: 'att-pdf-044',
    date: '2026-08-10',
    time: '15:30',
    studentId: 'std-10',
    studentCode: 'AGAN',
    studentName: 'Agan',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'Operasi hitung, kelipatan, dan faktor',
    tutorNotes: 'Konsep dasar FPB & KPK melalui pohon faktor.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-10T15:30:00Z',
  },
  {
    id: 'att-pdf-045',
    date: '2026-08-10',
    time: '15:30',
    studentId: 'std-7',
    studentCode: 'GEO',
    studentName: 'Geo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'Bahasa inggris have dan has',
    tutorNotes: 'Subjek tunggal vs jamak dengan have/has.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-10T15:30:00Z',
  },
  {
    id: 'att-pdf-046',
    date: '2026-08-10',
    time: '15:30',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 6,
    topic: 'Perkalian level 3, membaca dan menulis',
    tutorNotes: 'Dikte paragraf dan perkalian level 3.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-10T15:30:00Z',
  },
  {
    id: 'att-pdf-047',
    date: '2026-08-10',
    time: '15:30',
    studentId: 'std-4',
    studentCode: 'GYO',
    studentName: 'Gyo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 5,
    topic: 'Perkalian, bahasa kalimat tanya',
    tutorNotes: 'Membuat kalimat tanya 5W1H dan perkalian.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-10T15:30:00Z',
  },
  {
    id: 'att-pdf-048',
    date: '2026-08-10',
    time: '15:30',
    studentId: 'std-9',
    studentCode: 'KAYSA',
    studentName: 'Kaysa',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'Operasi hitung, kelipatan, dan faktor',
    tutorNotes: 'Latihan menentukan faktor persekutuan.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-10T15:30:00Z',
  },
  {
    id: 'att-pdf-049',
    date: '2026-08-10',
    time: '15:30',
    studentId: 'std-8',
    studentCode: 'ELVANO',
    studentName: 'Elvano',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Evaluasi makhluk hidup disekitar kita',
    tutorNotes: 'Mengerjakan tes formatif IPAS bab 1.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-10T15:30:00Z',
  },
  {
    id: 'att-pdf-050',
    date: '2026-08-11',
    time: '15:31',
    studentId: 'std-3',
    studentCode: 'BRIAN',
    studentName: 'Brian',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 5,
    topic: 'Perkalian dan membaca',
    tutorNotes: 'Membaca nyaring dan latihan perkalian.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-11T15:31:49Z',
  },
  {
    id: 'att-pdf-051',
    date: '2026-08-11',
    time: '15:52',
    studentId: 'std-11',
    studentCode: 'DOLKEN',
    studentName: 'Dolken',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'Operasi hitung, kelipatan, dan faktor',
    tutorNotes: 'Menghitung kelipatan bilangan dan perkalian bersusun.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-11T15:52:58Z',
  },
  {
    id: 'att-pdf-052',
    date: '2026-08-11',
    time: '15:53',
    studentId: 'std-6',
    studentCode: 'SILVIA',
    studentName: 'Silvia',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Perkalian puluhan',
    tutorNotes: 'Latihan perkalian bersusun satu tingkat.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-11T15:53:46Z',
  },
  {
    id: 'att-pdf-053',
    date: '2026-08-11',
    time: '15:54',
    studentId: 'std-14',
    studentCode: 'DEBI',
    studentName: 'Debi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Operasi hitung, kelipatan, dan faktor',
    tutorNotes: 'Latihan soal faktor persekutuan terbesar.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-11T15:54:01Z',
  },

  // --- Page 2: Records 54 to 107 ---
  {
    id: 'att-pdf-054',
    date: '2026-08-11',
    time: '15:54',
    studentId: 'std-17',
    studentCode: 'RAJA',
    studentName: 'Raja',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Soal cerita pecahan campuran dan desimal',
    tutorNotes: 'Penerapan soal cerita kehidupan sehari-hari.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-11T15:54:14Z',
  },
  {
    id: 'att-pdf-055',
    date: '2026-08-11',
    time: '19:12',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 7,
    topic: 'Evaluasi perkalian, membaca dan menulis',
    tutorNotes: 'Evaluasi mingguan kemampuan baca & hitung.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-11T19:12:29Z',
  },
  {
    id: 'att-pdf-056',
    date: '2026-08-12',
    time: '17:02',
    studentId: 'std-4',
    studentCode: 'GYO',
    studentName: 'Gyo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 6,
    topic: 'Latihan soal kalimat tanya',
    tutorNotes: 'Latihan menyusun kalimat tanya dengan benar.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-12T17:02:41Z',
  },
  {
    id: 'att-pdf-057',
    date: '2026-08-12',
    time: '17:02',
    studentId: 'std-2',
    studentCode: 'KIA',
    studentName: 'Kia',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'Perkalian level 2 (9-13)',
    tutorNotes: 'Mulai menghafal tabel perkalian 9-13.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-12T17:02:59Z',
  },
  {
    id: 'att-pdf-058',
    date: '2026-08-12',
    time: '17:03',
    studentId: 'std-3',
    studentCode: 'BRIAN',
    studentName: 'Brian',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 6,
    topic: 'Perkalian level 3 selesai',
    tutorNotes: 'Berhasil menuntaskan seluruh materi perkalian L3.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-12T17:03:10Z',
  },
  {
    id: 'att-pdf-059',
    date: '2026-08-12',
    time: '17:03',
    studentId: 'std-17',
    studentCode: 'RAJA',
    studentName: 'Raja',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 5,
    topic: 'Perkalian dan pembagian pecahan',
    tutorNotes: 'Mengubah pembagian pecahan menjadi perkalian kebalikan.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-12T17:03:58Z',
  },
  {
    id: 'att-pdf-060',
    date: '2026-08-12',
    time: '17:07',
    studentId: 'std-7',
    studentCode: 'GEO',
    studentName: 'Geo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Perkalian',
    tutorNotes: 'Latihan mandiri perkalian 5-10.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-12T17:07:14Z',
  },
  {
    id: 'att-pdf-061',
    date: '2026-08-12',
    time: '17:09',
    studentId: 'std-8',
    studentCode: 'ELVANO',
    studentName: 'Elvano',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 5,
    topic: 'IPAS Latihan soal siklus hidup makhluk hidup',
    tutorNotes: 'Mempelajari metamorfosis sempurna & tidak sempurna.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-12T17:09:38Z',
  },
  {
    id: 'att-pdf-062',
    date: '2026-08-12',
    time: '16:08',
    studentId: 'std-10',
    studentCode: 'AGAN',
    studentName: 'Agan',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Perkalian dan pembagian',
    tutorNotes: 'Operasi pembagian ratusan dengan pembagi satu angka.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-12T16:08:42Z',
  },
  {
    id: 'att-pdf-063',
    date: '2026-08-12',
    time: '16:09',
    studentId: 'std-20',
    studentCode: 'RANGGA',
    studentName: 'Rangga',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'Perkalian pecahan campuran, desimal',
    tutorNotes: 'Kombinasi operasi pecahan campuran dan desimal.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-12T16:09:19Z',
  },
  {
    id: 'att-pdf-064',
    date: '2026-08-12',
    time: '14:30',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 8,
    topic: 'Membaca, menulis, perkalian',
    tutorNotes: 'Membaca cerpen anak dan berhitung perkalian.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-12T14:30:35Z',
  },
  {
    id: 'att-pdf-065',
    date: '2026-08-13',
    time: '15:57',
    studentId: 'std-11',
    studentCode: 'DOLKEN',
    studentName: 'Dolken',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Faktor dan Kelipatan',
    tutorNotes: 'Menentukan FPB dari dua bilangan.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-13T15:57:52Z',
  },
  {
    id: 'att-pdf-066',
    date: '2026-08-13',
    time: '15:58',
    studentId: 'std-6',
    studentCode: 'SILVIA',
    studentName: 'Silvia',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'Memahami cerita',
    tutorNotes: 'Menjawab pertanyaan isi teks bacaan naratif.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-13T15:58:52Z',
  },
  {
    id: 'att-pdf-067',
    date: '2026-08-13',
    time: '15:59',
    studentId: 'std-12',
    studentCode: 'RARA',
    studentName: 'Rara',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Bilangan cacah',
    tutorNotes: 'Penjumlahan dan pengurangan bilangan cacah besar.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-13T15:59:13Z',
  },
  {
    id: 'att-pdf-068',
    date: '2026-08-13',
    time: '15:59',
    studentId: 'std-15',
    studentCode: 'TASYA',
    studentName: 'Tasya',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Menggambar & Seni Rupa',
    tutorNotes: 'Kreativitas menggambar perspektif dan pola warna.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-13T15:59:22Z',
  },
  {
    id: 'att-pdf-069',
    date: '2026-08-13',
    time: '16:01',
    studentId: 'std-14',
    studentCode: 'DEBI',
    studentName: 'Debi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'Menggambar & Seni Rupa',
    tutorNotes: 'Kreativitas seni visual dan gradasi warna.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-13T16:01:11Z',
  },
  {
    id: 'att-pdf-070',
    date: '2026-08-13',
    time: '16:02',
    studentId: 'std-13',
    studentCode: 'KAILA',
    studentName: 'Kaila',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Menggambar & Seni Rupa',
    tutorNotes: 'Eksplorasi tema flora dan fauna.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-13T16:02:43Z',
  },
  {
    id: 'att-pdf-071',
    date: '2026-08-13',
    time: '16:03',
    studentId: 'std-4',
    studentCode: 'GYO',
    studentName: 'Gyo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 7,
    topic: 'Perkalian level 3 1-10 dan cerita bahasa',
    tutorNotes: 'Menuntaskan soal cerita numerasi perkalian L3.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-13T16:03:28Z',
  },
  {
    id: 'att-pdf-072',
    date: '2026-08-13',
    time: '14:30',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 9,
    topic: 'Membaca dan perkalian',
    tutorNotes: 'Latihan pengucapan vokal dan perkalian 7-8.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-13T14:30:43Z',
  },
  {
    id: 'att-pdf-073',
    date: '2026-08-14',
    time: '19:00',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 10,
    topic: 'Membaca nya, i, u, e, o dan perkalian 100',
    tutorNotes: 'Mengenal diftong/kombinasi bunyi huruf dan perkalian ratusan.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-14T19:00:29Z',
  },
  {
    id: 'att-pdf-074',
    date: '2026-08-14',
    time: '19:01',
    studentId: 'std-10',
    studentCode: 'AGAN',
    studentName: 'Agan',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 5,
    topic: 'Perkalian pembagian soal cerita',
    tutorNotes: 'Pemecahan masalah soal kontekstual matematika.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-14T19:01:22Z',
  },
  {
    id: 'att-pdf-075',
    date: '2026-08-14',
    time: '19:01',
    studentId: 'std-9',
    studentCode: 'KAYSA',
    studentName: 'Kaysa',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Perkalian dan pembagian',
    tutorNotes: 'Latihan pembagian porogapit bersisa & tanpa sisa.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-14T19:01:44Z',
  },
  {
    id: 'att-pdf-076',
    date: '2026-08-14',
    time: '19:02',
    studentId: 'std-20',
    studentCode: 'RANGGA',
    studentName: 'Rangga',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Perkalian pecahan campuran, desimal',
    tutorNotes: 'Latihan soal persiapan ulangan harian.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-14T19:02:26Z',
  },
  {
    id: 'att-pdf-077',
    date: '2026-08-14',
    time: '19:02',
    studentId: 'std-11',
    studentCode: 'DOLKEN',
    studentName: 'Dolken',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 5,
    topic: 'Perkalian soal cerita',
    tutorNotes: 'Analisis soal cerita matematika operasi hitung.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-14T19:02:56Z',
  },
  {
    id: 'att-pdf-078',
    date: '2026-08-14',
    time: '19:03',
    studentId: 'std-7',
    studentCode: 'GEO',
    studentName: 'Geo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 5,
    topic: 'Perkalian level 3',
    tutorNotes: 'Menyelesaikan perkalian dua digit angka.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-14T19:03:19Z',
  },
  {
    id: 'att-pdf-079',
    date: '2026-08-14',
    time: '19:05',
    studentId: 'std-15',
    studentCode: 'TASYA',
    studentName: 'Tasya',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'Faktor dan Kelipatan 1',
    tutorNotes: 'Menentukan bilangan prima & faktor prima.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-14T19:05:25Z',
  },
  {
    id: 'att-pdf-080',
    date: '2026-08-14',
    time: '19:05',
    studentId: 'std-14',
    studentCode: 'DEBI',
    studentName: 'Debi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Perkalian soal cerita',
    tutorNotes: 'Menyelesaikan 5 soal cerita perkalian.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-14T19:05:32Z',
  },
  {
    id: 'att-pdf-081',
    date: '2026-08-14',
    time: '19:07',
    studentId: 'std-8',
    studentCode: 'ELVANO',
    studentName: 'Elvano',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 6,
    topic: 'SAS English',
    tutorNotes: 'Persiapan Sumatif Akhir Semester (SAS) Bahasa Inggris.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-14T19:07:01Z',
  },
  {
    id: 'att-pdf-082',
    date: '2026-08-15',
    time: '19:38',
    studentId: 'std-23',
    studentCode: 'ZIDANE',
    studentName: 'Zidane',
    classType: 'Privat',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'Perkalian aljabar',
    tutorNotes: 'Perkalian suku dua aljabar (ax + b)(cx + d).',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-15T19:38:53Z',
  },
  {
    id: 'att-pdf-083',
    date: '2026-08-16',
    time: '18:24',
    studentId: 'std-24',
    studentCode: 'VALEN',
    studentName: 'Valen',
    classType: 'Privat',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Bilangan berpangkat',
    tutorNotes: 'Pangkat pecahan dan bentuk akar tingkat lanjut.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-16T18:24:22Z',
  },
  {
    id: 'att-pdf-084',
    date: '2026-08-17',
    time: '21:52',
    studentId: 'std-21',
    studentCode: 'JUNA',
    studentName: 'Juna',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Perkalian dan pembagian pecahan',
    tutorNotes: 'Latihan operasi hitung pecahan tingkat kelas 6.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-17T21:52:09Z',
  },
  {
    id: 'att-pdf-085',
    date: '2026-08-17',
    time: '21:52',
    studentId: 'std-9',
    studentCode: 'KAYSA',
    studentName: 'Kaysa',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 5,
    topic: 'Perkalian dan pembagian soal cerita',
    tutorNotes: 'Latihan soal terapan matematika.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-17T21:52:34Z',
  },
  {
    id: 'att-pdf-086',
    date: '2026-08-17',
    time: '21:52',
    studentId: 'std-18',
    studentCode: 'AURA',
    studentName: 'Aura',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'Perkalian dan pembagian pecahan',
    tutorNotes: 'Menuntaskan modul pecahan bab 1.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-17T21:52:40Z',
  },
  {
    id: 'att-pdf-087',
    date: '2026-08-17',
    time: '21:52',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 11,
    topic: 'Bahasa inggris Greeting, perkalian',
    tutorNotes: 'Materi salam/sapaan bahasa Inggris & perkalian.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-17T21:52:46Z',
  },
  {
    id: 'att-pdf-088',
    date: '2026-08-17',
    time: '21:52',
    studentId: 'std-17',
    studentCode: 'RAJA',
    studentName: 'Raja',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 6,
    topic: 'Bahasa inggris was, were',
    tutorNotes: 'Penggunaan to be past tense was dan were.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-17T21:52:53Z',
  },
  {
    id: 'att-pdf-089',
    date: '2026-08-17',
    time: '21:53',
    studentId: 'std-7',
    studentCode: 'GEO',
    studentName: 'Geo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 6,
    topic: 'Perkalian level 3',
    tutorNotes: 'Penyelesaian soal latihan cepat perkalian.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-17T21:53:00Z',
  },
  {
    id: 'att-pdf-090',
    date: '2026-08-18',
    time: '18:34',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 12,
    topic: 'Perkalian dan Inggris',
    tutorNotes: 'Review kosakata Inggris dan perkalian level 3.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-18T18:34:59Z',
  },
  {
    id: 'att-pdf-091',
    date: '2026-08-18',
    time: '18:35',
    studentId: 'std-17',
    studentCode: 'RAJA',
    studentName: 'Raja',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 7,
    topic: 'Perkalian dan pembagian pecahan',
    tutorNotes: 'Latihan soal pecahan campuran kompleks.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-18T18:35:19Z',
  },
  {
    id: 'att-pdf-092',
    date: '2026-08-18',
    time: '18:35',
    studentId: 'std-11',
    studentCode: 'DOLKEN',
    studentName: 'Dolken',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 6,
    topic: 'Perkalian dan pembagian',
    tutorNotes: 'Pembagian puluhan dan ratusan.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-18T18:35:30Z',
  },
  {
    id: 'att-pdf-093',
    date: '2026-08-18',
    time: '18:36',
    studentId: 'std-12',
    studentCode: 'RARA',
    studentName: 'Rara',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'PR perkalian dan pembagian',
    tutorNotes: 'Membahas tuntas PR sekolah tentang operasi perkalian.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-18T18:36:00Z',
  },
  {
    id: 'att-pdf-094',
    date: '2026-08-18',
    time: '18:36',
    studentId: 'std-4',
    studentCode: 'GYO',
    studentName: 'Gyo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 8,
    topic: 'Perkalian, bahasa Subjek, predikat, objek',
    tutorNotes: 'Tata bahasa SPOK dan latihan perkalian.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-18T18:36:33Z',
  },
  {
    id: 'att-pdf-095',
    date: '2026-08-18',
    time: '18:36',
    studentId: 'std-10',
    studentCode: 'AGAN',
    studentName: 'Agan',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 6,
    topic: 'PR perkalian dan pembagian',
    tutorNotes: 'Bahas PR pembagian porogapit dari sekolah.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-18T18:36:50Z',
  },
  {
    id: 'att-pdf-096',
    date: '2026-08-18',
    time: '18:37',
    studentId: 'std-21',
    studentCode: 'JUNA',
    studentName: 'Juna',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'PR perkalian pecahan',
    tutorNotes: 'Menyelesaikan PR perkalian pecahan desimal.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-18T18:37:02Z',
  },
  {
    id: 'att-pdf-097',
    date: '2026-08-18',
    time: '18:37',
    studentId: 'std-9',
    studentCode: 'KAYSA',
    studentName: 'Kaysa',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 6,
    topic: 'Latihan Soal & Pendalaman Materi',
    tutorNotes: 'Mengerjakan lembar kerja pendalaman materi.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-18T18:37:02Z',
  },
  {
    id: 'att-pdf-098',
    date: '2026-08-19',
    time: '17:30',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 13,
    topic: 'Bahasa inggris perkalian dan membaca',
    tutorNotes: 'Latihan kosakata bahasa Inggris dan membaca cerita.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-19T17:30:37Z',
  },
  {
    id: 'att-pdf-099',
    date: '2026-08-19',
    time: '17:30',
    studentId: 'std-21',
    studentCode: 'JUNA',
    studentName: 'Juna',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 3,
    topic: 'PR perkalian pecahan',
    tutorNotes: 'Membahas soal-soal pecahan PR sekolah.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-19T17:30:37Z',
  },
  {
    id: 'att-pdf-100',
    date: '2026-08-19',
    time: '17:30',
    studentId: 'std-20',
    studentCode: 'RANGGA',
    studentName: 'Rangga',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 5,
    topic: 'PR perkalian pecahan',
    tutorNotes: 'Menyelesaikan PR pecahan dengan nilai memuaskan.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-19T17:30:37Z',
  },
  {
    id: 'att-pdf-101',
    date: '2026-08-19',
    time: '17:30',
    studentId: 'std-2',
    studentCode: 'KIA',
    studentName: 'Kia',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Perkalian',
    tutorNotes: 'Latihan hafalan perkalian dan soal tulis.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-19T17:30:37Z',
  },
  {
    id: 'att-pdf-102',
    date: '2026-08-19',
    time: '17:30',
    studentId: 'std-17',
    studentCode: 'RAJA',
    studentName: 'Raja',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 8,
    topic: 'Perkenalan Rasio',
    tutorNotes: 'Pengenalan konsep rasio/perbandingan dua besaran.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-19T17:30:37Z',
  },
  {
    id: 'att-pdf-103',
    date: '2026-08-19',
    time: '17:30',
    studentId: 'std-7',
    studentCode: 'GEO',
    studentName: 'Geo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 7,
    topic: 'Bahasa inggris Greeting, perkalian',
    tutorNotes: 'Greeting conversation dan quiz perkalian cepat.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-19T17:30:37Z',
  },
  {
    id: 'att-pdf-104',
    date: '2026-08-20',
    time: '19:52',
    studentId: 'std-17',
    studentCode: 'RAJA',
    studentName: 'Raja',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 9,
    topic: 'Latihan soal LCC',
    tutorNotes: 'Simulasi Lomba Cerdas Cermat matematika & sains.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-20T19:52:24Z',
  },
  {
    id: 'att-pdf-105',
    date: '2026-08-20',
    time: '19:52',
    studentId: 'std-2',
    studentCode: 'KIA',
    studentName: 'Kia',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 5,
    topic: 'Perkalian 21-25',
    tutorNotes: 'Latihan perkalian angka puluhan 21-25.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-20T19:52:36Z',
  },
  {
    id: 'att-pdf-106',
    date: '2026-08-20',
    time: '19:52',
    studentId: 'std-4',
    studentCode: 'GYO',
    studentName: 'Gyo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 9,
    topic: 'Perkalian dan melengkapi kalimat tanya',
    tutorNotes: 'Latihan kalimat tanya apa, siapa, di mana, mengapa.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-20T19:52:50Z',
  },
  {
    id: 'att-pdf-107',
    date: '2026-08-20',
    time: '19:52',
    studentId: 'std-3',
    studentCode: 'BRIAN',
    studentName: 'Brian',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 7,
    topic: 'Perkalian',
    tutorNotes: 'Mengerjakan lembar kerja perkalian dengan mandiri.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-20T19:52:57Z',
  },

  // --- Page 3: Records 108 to 145 ---
  {
    id: 'att-pdf-108',
    date: '2026-08-20',
    time: '19:53',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 14,
    topic: 'Perkalian dan membaca',
    tutorNotes: 'Membaca nyaring paragraf cerita pendek & perkalian.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-20T19:53:06Z',
  },
  {
    id: 'att-pdf-109',
    date: '2026-08-20',
    time: '19:53',
    studentId: 'std-9',
    studentCode: 'KAYSA',
    studentName: 'Kaysa',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 7,
    topic: 'Perkalian, kelipatan, dan faktor',
    tutorNotes: 'Kombinasi soal KPK dan perkalian cepat.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-20T19:53:12Z',
  },
  {
    id: 'att-pdf-110',
    date: '2026-08-20',
    time: '19:53',
    studentId: 'std-21',
    studentCode: 'JUNA',
    studentName: 'Juna',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Perkalian pecahan',
    tutorNotes: 'Mengerjakan latihan soal perkalian pecahan.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-20T19:53:20Z',
  },
  {
    id: 'att-pdf-111',
    date: '2026-08-20',
    time: '19:53',
    studentId: 'std-22',
    studentCode: 'AGHA',
    studentName: 'Agha',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Perkalian pecahan',
    tutorNotes: 'Perkalian pecahan biasa dan campuran.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-20T19:53:51Z',
  },
  {
    id: 'att-pdf-112',
    date: '2026-08-20',
    time: '20:01',
    studentId: 'std-25',
    studentCode: 'ATHAR',
    studentName: 'Athar',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Dasar Perkalian',
    tutorNotes: 'Pengenalan konsep perkalian sebagai penjumlahan berulang.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-20T20:01:25Z',
  },
  {
    id: 'att-pdf-113',
    date: '2026-08-21',
    time: '15:05',
    studentId: 'std-11',
    studentCode: 'DOLKEN',
    studentName: 'Dolken',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 7,
    topic: 'Perkalian',
    tutorNotes: 'Perkalian bersusun ratusan dikali puluhan.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-21T15:05:20Z',
  },
  {
    id: 'att-pdf-114',
    date: '2026-08-21',
    time: '15:05',
    studentId: 'std-10',
    studentCode: 'AGAN',
    studentName: 'Agan',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 7,
    topic: 'Mengenal pecahan',
    tutorNotes: 'Pengenalan konsep pecahan senilai dan gambar pecahan.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-21T15:05:28Z',
  },
  {
    id: 'att-pdf-115',
    date: '2026-08-21',
    time: '15:05',
    studentId: 'std-6',
    studentCode: 'SILVIA',
    studentName: 'Silvia',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Perkalian',
    tutorNotes: 'Latihan perkalian angka 4-7.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-21T15:05:36Z',
  },
  {
    id: 'att-pdf-116',
    date: '2026-08-21',
    time: '15:05',
    studentId: 'std-7',
    studentCode: 'GEO',
    studentName: 'Geo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 8,
    topic: 'Perkalian',
    tutorNotes: 'Peningkatan kecepatan berhitung perkalian.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-21T15:05:57Z',
  },
  {
    id: 'att-pdf-117',
    date: '2026-08-21',
    time: '15:06',
    studentId: 'std-3',
    studentCode: 'BRIAN',
    studentName: 'Brian',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 8,
    topic: 'Perkalian',
    tutorNotes: 'Evaluasi mingguan kemampuan berhitung.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-21T15:06:13Z',
  },
  {
    id: 'att-pdf-118',
    date: '2026-08-21',
    time: '15:06',
    studentId: 'std-12',
    studentCode: 'RARA',
    studentName: 'Rara',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Bahasa inggris',
    tutorNotes: 'Pengenalan kosakata daily routine dalam bahasa Inggris.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-21T15:06:31Z',
  },
  {
    id: 'att-pdf-119',
    date: '2026-08-21',
    time: '17:38',
    studentId: 'std-17',
    studentCode: 'RAJA',
    studentName: 'Raja',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 10,
    topic: 'Persiapan LCC Matematika, IPAS',
    tutorNotes: 'Pemantapan materi LCC matematika bab pecahan dan IPAS.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-21T17:38:21Z',
  },
  {
    id: 'att-pdf-120',
    date: '2026-08-21',
    time: '17:39',
    studentId: 'std-20',
    studentCode: 'RANGGA',
    studentName: 'Rangga',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 6,
    topic: 'Operasi Desimal',
    tutorNotes: 'Penjumlahan, pengurangan, dan perkalian bilangan desimal.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-21T17:39:08Z',
  },
  {
    id: 'att-pdf-121',
    date: '2026-08-21',
    time: '17:39',
    studentId: 'std-8',
    studentCode: 'ELVANO',
    studentName: 'Elvano',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 7,
    topic: 'IPAS Latihan soal Makhluk hidup disekitar kita',
    tutorNotes: 'Pembahasan ekosistem dan rantai makanan.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-21T17:39:23Z',
  },
  {
    id: 'att-pdf-122',
    date: '2026-08-21',
    time: '18:29',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 15,
    topic: 'Perkalian ratusan, membaca dan menulis',
    tutorNotes: 'Berhitung perkalian ratusan dengan bantuan tabel.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-21T18:29:31Z',
  },
  {
    id: 'att-pdf-123',
    date: '2026-08-21',
    time: '18:37',
    studentId: 'std-21',
    studentCode: 'JUNA',
    studentName: 'Juna',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 5,
    topic: 'Tugas Agama Surat Ad dhuha',
    tutorNotes: 'Hafalan dan memahami makna surat Ad-Dhuha.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-21T18:37:34Z',
  },
  {
    id: 'att-pdf-124',
    date: '2026-08-21',
    time: '18:37',
    studentId: 'std-9',
    studentCode: 'KAYSA',
    studentName: 'Kaysa',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 8,
    topic: 'Kelipatan dan faktor',
    tutorNotes: 'Evaluasi pemahaman materi FPB dan KPK.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-21T18:37:45Z',
  },
  {
    id: 'att-pdf-125',
    date: '2026-08-22',
    time: '20:55',
    studentId: 'std-23',
    studentCode: 'ZIDANE',
    studentName: 'Zidane',
    classType: 'Privat',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Perkalian 4 dan perkalian aljabar',
    tutorNotes: 'Latihan soal menyederhanakan pecahan aljabar.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-22T20:55:20Z',
  },
  {
    id: 'att-pdf-126',
    date: '2026-08-23',
    time: '19:20',
    studentId: 'std-9',
    studentCode: 'KAYSA',
    studentName: 'Kaysa',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 9,
    topic: 'Tugas b indo + porogapit',
    tutorNotes: 'Menyelesaikan tugas bahasa Indonesia dan latihan porogapit.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-23T19:20:08Z',
  },
  {
    id: 'att-pdf-127',
    date: '2026-08-23',
    time: '19:20',
    studentId: 'std-22',
    studentCode: 'AGHA',
    studentName: 'Agha',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Assessment sumatif harian 2',
    tutorNotes: 'Mengerjakan paket soal asesmen sumatif.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-23T19:20:47Z',
  },
  {
    id: 'att-pdf-128',
    date: '2026-08-23',
    time: '19:21',
    studentId: 'std-24',
    studentCode: 'VALEN',
    studentName: 'Valen',
    classType: 'Privat',
    status: 'Hadir',
    sessionNumber: 5,
    topic: 'TKA matematika',
    tutorNotes: 'Tes Kemampuan Akademik (TKA) Matematika SMP.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-23T19:21:07Z',
  },
  {
    id: 'att-pdf-129',
    date: '2026-08-24',
    time: '17:32',
    studentId: 'std-20',
    studentCode: 'RANGGA',
    studentName: 'Rangga',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 7,
    topic: 'Operasi Desimal',
    tutorNotes: 'Operasi pembagian angka desimal bersusun.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-24T17:32:11Z',
  },
  {
    id: 'att-pdf-130',
    date: '2026-08-24',
    time: '17:32',
    studentId: 'std-17',
    studentCode: 'RAJA',
    studentName: 'Raja',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 11,
    topic: 'Bahasa Inggris was, were',
    tutorNotes: 'Latihan mengubah kalimat present ke past tense.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-24T17:32:11Z',
  },
  {
    id: 'att-pdf-131',
    date: '2026-08-24',
    time: '17:32',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 16,
    topic: 'Membaca, menulis, perkalian level 4',
    tutorNotes: 'Mencapai perkalian level 4 dengan perkembangan pesat.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-24T17:32:11Z',
  },
  {
    id: 'att-pdf-132',
    date: '2026-08-24',
    time: '17:32',
    studentId: 'std-3',
    studentCode: 'BRIAN',
    studentName: 'Brian',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 9,
    topic: 'Ekspresi, kata tanya, memahami bacaan',
    tutorNotes: 'Membaca intonasi kalimat tanya dan ekspresi.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-24T17:32:11Z',
  },
  {
    id: 'att-pdf-133',
    date: '2026-08-24',
    time: '17:32',
    studentId: 'std-7',
    studentCode: 'GEO',
    studentName: 'Geo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 9,
    topic: 'Bahasa inggris greeting',
    tutorNotes: 'Praktik dialog greeting dan farewell.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-24T17:32:11Z',
  },
  {
    id: 'att-pdf-134',
    date: '2026-08-24',
    time: '17:32',
    studentId: 'std-4',
    studentCode: 'GYO',
    studentName: 'Gyo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 10,
    topic: 'Ekspresi, kata tanya, memahami bacaan',
    tutorNotes: 'Membaca teks cerita dan menjawab pertanyaan bacaan.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-24T17:32:11Z',
  },
  {
    id: 'att-pdf-135',
    date: '2026-08-25',
    time: '16:38',
    studentId: 'std-11',
    studentCode: 'DOLKEN',
    studentName: 'Dolken',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 8,
    topic: 'Perkalian L3 1-5, pembagian L3 1-5',
    tutorNotes: 'Operasi perkalian dan pembagian level 3 angka 1-5.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-25T16:38:26Z',
  },
  {
    id: 'att-pdf-136',
    date: '2026-08-25',
    time: '16:38',
    studentId: 'std-17',
    studentCode: 'RAJA',
    studentName: 'Raja',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 12,
    topic: 'My past activity',
    tutorNotes: 'Menuliskan 5 aktivitas masa lampau (Simple Past Tense).',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-25T16:38:38Z',
  },
  {
    id: 'att-pdf-137',
    date: '2026-08-25',
    time: '16:38',
    studentId: 'std-3',
    studentCode: 'BRIAN',
    studentName: 'Brian',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 10,
    topic: 'Kata tanya dan melengkapi kalimat tanya',
    tutorNotes: 'Menulis kata tanya yang tepat pada kalimat rumpang.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-25T16:38:47Z',
  },
  {
    id: 'att-pdf-138',
    date: '2026-08-25',
    time: '18:19',
    studentId: 'std-19',
    studentCode: 'NAILA',
    studentName: 'Naila',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 1,
    topic: 'Perkalian pecahan campuran dan bil. asli',
    tutorNotes: 'Perkalian pecahan campuran dengan bilangan bulat positif.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-25T18:19:05Z',
  },
  {
    id: 'att-pdf-139',
    date: '2026-08-25',
    time: '18:19',
    studentId: 'std-18',
    studentCode: 'AURA',
    studentName: 'Aura',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 4,
    topic: 'Perkalian pecahan campuran dan bil. asli',
    tutorNotes: 'Menyelesaikan 8 latihan soal pecahan campuran.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-25T18:19:18Z',
  },
  {
    id: 'att-pdf-140',
    date: '2026-08-25',
    time: '18:19',
    studentId: 'std-5',
    studentCode: 'ABI',
    studentName: 'Abi',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 17,
    topic: 'Membaca, menulis, evaluasi perkalian',
    tutorNotes: 'Evaluasi harian membaca pemahaman dan perkalian.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-25T18:19:41Z',
  },
  {
    id: 'att-pdf-141',
    date: '2026-08-25',
    time: '17:13',
    studentId: 'std-25',
    studentCode: 'ATHAR',
    studentName: 'Athar',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 2,
    topic: 'Perkalian 1-4',
    tutorNotes: 'Latihan penguasaan perkalian angka 1 sampai 4.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-25T17:13:31Z',
  },
  {
    id: 'att-pdf-142',
    date: '2026-08-26',
    time: '17:13',
    studentId: 'std-17',
    studentCode: 'RAJA',
    studentName: 'Raja',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 13,
    topic: 'Kesamaan rasio',
    tutorNotes: 'Menentukan rasio yang ekuivalen / senilai.',
    tutorName: 'Kak Sarah Amalia, S.Si.',
    createdAt: '2026-08-26T17:13:02Z',
  },
  {
    id: 'att-pdf-143',
    date: '2026-08-26',
    time: '17:13',
    studentId: 'std-7',
    studentCode: 'GEO',
    studentName: 'Geo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 10,
    topic: 'Perkalian L3 18-22',
    tutorNotes: 'Latihan perkalian level 3 nomor 18 sampai 22.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-26T17:13:09Z',
  },
  {
    id: 'att-pdf-144',
    date: '2026-08-26',
    time: '17:13',
    studentId: 'std-4',
    studentCode: 'GYO',
    studentName: 'Gyo',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 11,
    topic: 'Perkalian L2 21-25, kewarganegaraan taat aturan',
    tutorNotes: 'Pendidikan Pancasila norma aturan & berhitung perkalian L2.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-26T17:13:15Z',
  },
  {
    id: 'att-pdf-145',
    date: '2026-08-26',
    time: '17:13',
    studentId: 'std-8',
    studentCode: 'ELVANO',
    studentName: 'Elvano',
    classType: 'Grup',
    status: 'Hadir',
    sessionNumber: 8,
    topic: 'Evaluasi makhluk hidup disekitar kita',
    tutorNotes: 'Menyelesaikan modul review IPAS tema makhluk hidup.',
    tutorName: 'Kak Dimas Pratama, M.Pd.',
    createdAt: '2026-08-26T17:13:22Z',
  },
];
